
spring:
  datasource:
    username: bookspf
    password: bookspf
    url: jdbc:mysql://localhost:3306/Bookspf?useSSl=false&serverTimezone=UTC
  mvc:
    #资源文件的访问路径，例如：http://127.0.0.1:8080/bookimg/1.jpg
    static-path-pattern: /**
  resources:
    #资源文件存放的位置
    static-locations: classpath:\static,file:\D:\LocalProject

